# Generated by Django 3.0.7 on 2020-06-14 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20200613_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='level',
            new_name='stage',
        ),
    ]
