# Generated by Django 3.0.7 on 2020-06-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20200614_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stage',
            field=models.CharField(choices=[('N1', 'Nursery One'), ('N2', 'Nursery Two'), ('K1', 'K.G One'), ('K2', 'K.G Two'), ('1', 'Stage 1'), ('2', 'Stage 2'), ('3', 'Stage 3'), ('4', 'Stage 4'), ('5', 'Stage 5'), ('6', 'Stage 6'), ('F1', 'Form One'), ('F2', 'Form Two'), ('F3', 'Form Three')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
