# Generated by Django 3.0.7 on 2020-06-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20200614_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stage',
            field=models.CharField(choices=[('Nursery One', 'Nursery One'), ('Nursery Two', 'Nursery Two'), ('K. G 1', 'K.G One'), ('K. G 2', 'K.G Two'), ('Stage 1', 'Stage 1'), ('Stage 2', 'Stage 2'), ('Stage 3', 'Stage 3'), ('Stage 4', 'Stage 4'), ('Stage 5', 'Stage 5'), ('Stage 6', 'Stage 6'), ('Form 1', 'Form One'), ('Form 2', 'Form Two'), ('Form 3', 'Form Three')], max_length=20),
        ),
    ]
